insert into team(id, team_id, name, description, created_at) values (1, 'public', '公共技术', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (2, 'sns', '社区', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (3, 'book', '读书', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (4, 'movie', '电影', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (5, 'music', '音乐', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (7, 'biz', '商务', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (8, 'safe', '安全', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (9, 'platform', '平台', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (10, 'algorithm', '算法', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (11, 'mobile', '移动', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (12, 'alpha', '阿尔法城', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (13, 'ad', '广告平台', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (14, 'f2e', '前端', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (15, 'intra', '内网', '', '2013-03-01');
insert into team(id, team_id, name, description, created_at) values (16, 'data', '数据分析', '', '2013-03-01');
insert into team_user_relationship(team_id, user_id, identity) values(1, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(2, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(3, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(4, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(5, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(6, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(7, 'xingben', 2);
insert into team_user_relationship(team_id, user_id, identity) values(8, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(9, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(10, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(11, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(12, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(13, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(14, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(15, 'qingfeng', 2);
insert into team_user_relationship(team_id, user_id, identity) values(16, 'qingfeng', 2);
